-- Add new DocumentType enum values for UAT KYC v3
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CIVIL_EXTRACT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'RESIDENCE_PERMIT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'STAFF_UPLOAD';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'OTHER';
